services:
  - type: web
    name: flawless-liqpay-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LIQPAY_PUBLIC_KEY
        sync: false
      - key: LIQPAY_PRIVATE_KEY
        sync: false
      - key: CURRENCY
        value: UAH
      - key: ALLOWED_USER_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
